CREATE TABLE LOGINS (
    ID_USUARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOME_USUARIO VARCHAR(100) NOT NULL,
	LOGIN_USUARIO VARCHAR(20) NOT NULL UNIQUE,
	SENHA_USUARIO VARCHAR(256) NOT NULL,
	EMAIL VARCHAR(250) NOT NULL,
	DATA_CRIACAO SMALLDATETIME NOT NULL
);

CREATE TABLE MARCAS_VEICULOS (
    ID_MARCA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MODELOS_VEICULOS (
    ID_MODELO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE,
	ID_MARCA INT NOT NULL,
	CONSTRAINT FK_MARCA_MODELO_VEICULOS FOREIGN KEY (ID_MARCA) REFERENCES MARCAS_VEICULOS (ID_MARCA)
);

CREATE TABLE CILINDRADA_VEICULOS (
    ID_CILINDRADA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE PECAS (
    ID_PECA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL UNIQUE,	
);

CREATE TABLE MARCAS_PECAS (
    ID_MARCA_PECAS INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL UNIQUE	
);

CREATE TABLE HISTORICO_PRECOS_PECAS (
    ID_HIST_PRECO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PRECO DECIMAL(14,2) NOT NULL,
	CUSTO DECIMAL(14,2) NULL,
	ULTIMO_PRECO SMALLDATETIME NOT NULL,
	ID_PRECO_PECA INT NOT NULL
	CONSTRAINT FK_LISTA_PRECO_PECAS FOREIGN KEY (ID_PRECO_PECA) REFERENCES LISTA_PRECO_PECAS (ID_PRECO_PECA)
);

CREATE TABLE ANO_MODELO_VEICULO (
    ID_ANO_MOD_VEIC INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL UNIQUE	
);

CREATE TABLE LISTA_PRECO_PECAS (
    ID_PRECO_PECA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_MARCA_PECAS INT NOT NULL,
	ID_MODELO INT NOT NULL,
	ID_PECA INT NOT NULL,
	STATUS char(1) NOT NULL,
	CODIGO VARCHAR(50) NULL,
	CONSTRAINT FK_MARCA_PECAS FOREIGN KEY (ID_MARCA_PECAS) REFERENCES MARCAS_PECAS (ID_MARCA_PECAS),
	CONSTRAINT FK_MODELOS_VEICULOS FOREIGN KEY (ID_MODELO) REFERENCES MODELOS_VEICULOS (ID_MODELO),
	CONSTRAINT FK_PECAS FOREIGN KEY (ID_PECA) REFERENCES PECAS (ID_PECA)	
);

CREATE TABLE LISTA_ANO_MODELO_PRECO (
    ID_ANO_MOD_PRECO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_PRECO_PECA INT NOT NULL,
	ID_ANO_MOD_VEIC INT NOT NULL,
	CONSTRAINT FK_LISTA_PRECO_PECAS FOREIGN KEY (ID_PRECO_PECA) REFERENCES LISTA_PRECO_PECAS (ID_PRECO_PECA),
	CONSTRAINT FK_ANO_MODELO_VEICULO FOREIGN KEY (ID_ANO_MOD_VEIC) REFERENCES ANO_MODELO_VEICULO (ID_ANO_MOD_VEIC)
);

CREATE TABLE HISTORICO_PRECOS_PECAS (
    ID_HIST_PRECO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PRECO DECIMAL(14,2) NOT NULL,
	CUSTO DECIMAL(14,2) NULL,
	ULTIMO_PRECO SMALLDATETIME NOT NULL,
	ID_PRECO_PECA INT NOT NULL
	CONSTRAINT FK_LISTA_PRECO_PECAS_HISTORICO FOREIGN KEY (ID_PRECO_PECA) REFERENCES LISTA_PRECO_PECAS (ID_PRECO_PECA)
);

CREATE TABLE ESTOQUE_PECAS (
    ID_ESTOQUE_PECAS INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    QTDE_ESTOQUE INT NOT NULL,
	ID_PRECO_PECA INT NOT NULL UNIQUE
	CONSTRAINT FK_LISTA_PRECO_PECAS_ESTOQUE FOREIGN KEY (ID_PRECO_PECA) REFERENCES LISTA_PRECO_PECAS (ID_PRECO_PECA)
);